### ISSUE TITLE
Visual Bug

### ISSUE THREAD

**Issue by Javajoe0224** [Darkosto/SkyFactory4#16]
There is a visual bug with compact chest (ComPatchedStorage Mod). If you open the chest and remove or add anything the contents disappear. You can close and re-open the chest and everything is back. This happened after the 4.0.2 update and I'm on the Seven Seas map.

**Comment by justinrusso** [comment]
This is not the place to report issues. You can find it here: https://github.com/Darkosto/SkyFactory4Issues/issues

The issue has already been reported here https://github.com/Darkosto/SkyFactory4Issues/issues/449
